server.port=8085

spring.application.name=Travel2030

spring.datasource.url=jdbc:mysql://localhost:3306/travel2030?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

app.jwt.secret=LZeX4pzsCDQXUPYXZ5zhYJNxrHHAzvGfh+RpdmOgZGf+FpC1seU5Tuo+T8L7qHlaSL4mk+lsglunIdnSuqAQsg==
app.jwt.expiration-ms=86400000
app.jwt.refresh-expiration-ms=604800000

app.cors.allowed-origins=http://localhost:4200

spring.mail.host=localhost
spring.mail.port=2525
spring.mail.username=noreply@travel2030.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

logging.level.com.example.backend=DEBUG
logging.level.org.springframework.security=DEBUG
